---
- name: In-Memory Inventory
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  vars:
    guid: "{{ lookup('ENV','GUID') }}"
    home: "{{ lookup('ENV','HOME') }}"
    internal_domain: "example.com"

  roles:
    - memory-inv
    - osp-config

  post_tasks:
    - name: Print hosts
      debug:
        var=groups
